### ISSUE TITLE
Property for making a FlexItem also a container

### ISSUE THREAD

**Issue by t3db0t** [SaraVieira/styled-flex-component#11]
There are occasions when you might put `display:flex` in a `FlexItem`—should there be an API for this? Not sure what would make the most sense.

BTW I LOVE this package and I use it CONSTANTLY. <3

**Comment by LuigiDerson** [comment]
maybe with the :nth-child() selector?

`&:nth-child($(props => props.childPosition)) {
 display: flex;
}`

**Comment by ughitsaaron** [comment]
Hey @t3db0t, I just recently came across this use case. `styled-components` components provides you with an `as` property that you can use in these situations. That allows you to retain all the styles you've applied to your component while replacing what's being rendered. Since `Flex` and `FlexItems` are both styled components already, you get this for free. For instance, 

```javascript
import Flex, { FlexItem } from 'styled-flex-component';

function Greeting() {
  return (
    <Flex column>
      <Flex>{/* ... */}</Flex>
      <Flex>
        <Flex as={FlexItem} grow={1}>
          {/* ... */}
        </Flex>
      </Flex>
    </Flex>
  );
}
```

**Comment by t3db0t** [comment]
Oh cool! Thanks so much!
